# Generated by Django 6.0.3 on 2026-03-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainant_name', models.CharField(max_length=100)),
                ('complainant_email', models.EmailField(max_length=254)),
                ('complainant_phone', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Billing', 'Billing'), ('Service', 'Service'), ('Product', 'Product'), ('Delivery', 'Delivery'), ('Other', 'Other')], max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Escalated', 'Escalated'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
